export const fieldNamesInSpanish: { [key: string]: string } = {
  'file': 'cv',
  'image': 'imagen',
  'name': 'nombre',
  'paternalSurname': 'apellido paterno',
  'maternalSurname': 'apellido materno',
  'callPrefix': 'prefijo',
  'cellPhoneNumber': 'número de celular',
  'description': 'descripción',
  'linkedinLink': 'enlace de LinkedIn',
  'githubLink': 'enlace de GitHub',
  'initialAmount': 'cantidad inicial',
  'finalAmount': 'cantidad final',
  'countryId': 'país',
  'cityId': 'ciudad',
  'currencyId': 'moneda',
  'profileId': 'perfil',
  'skill': 'habilidad',
  'years': 'años de experiencia',
  'languageId': 'idioma',
  'levelId': 'nivel de idioma',
  'numberOfStars': 'número de estrellas',
  'startDate': 'fecha de inicio',
  'endDate': 'fecha de fin',
  'degree': 'grado',
  'career': 'carrera',
  'company': 'empresa',
  'position': 'posición',
  'educationalInstitute': 'institución educativa',
};
